name: Hourly Appointment Reminders

on:
  schedule:
    # Ejecutar en el minuto 0 de cada hora
    - cron: '0 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente si es necesario

jobs:
  ping_vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Hit the Hourly Cron Endpoint
        env:
          VERCEL_URL: "https://chatbot-crm-xi.vercel.app/api/campaign?action=hourly_reminder"
          AUTH_TOKEN: "nexus_secure_123"
        run: |
          curl -X POST -H "Authorization: Bearer $AUTH_TOKEN" $VERCEL_URL
